"""
Spielkonfiguration fuer Schiffe-Versenken
Enthaelt alle Konstanten, Farben und Spielregeln
"""

# Fenster
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
TITLE = "Schiffe Versenken - Navy Command"
WINDOW_RESIZABLE = True
WINDOW_FULLSCREEN = False
WINDOW_FULLSCREEN_CHANGED = False

# Spielfeld
GRID_SIZE = 10  # 10x10 Spielfeld
CELL_SIZE = 60
GRID_GAP_X = 200
GRID_TOP_MARGIN = 250

# Layout (wird in update_layout gesetzt)
PLAYER_GRID_X = 0
COMPUTER_GRID_X = 0
GRID_OFFSET_Y = GRID_TOP_MARGIN

# Farben
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_BLUE = (65, 105, 225)
COLOR_RED = (220, 20, 60)
COLOR_GREEN = (34, 139, 34)
COLOR_GRAY = (128, 128, 128)
COLOR_DARK_GRAY = (64, 64, 64)
COLOR_LIGHT_GRAY = (192, 192, 192)
COLOR_YELLOW = (255, 215, 0)

# Button-Einstellungen
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_COLOR = COLOR_BLUE
BUTTON_HOVER_COLOR = (100, 140, 255)
BUTTON_TEXT_COLOR = COLOR_WHITE

# Schiffstypen: (Name, Laenge, Anzahl)
SHIP_TYPES = [
    ("Schlachtschiff", 5, 1),
    ("Kreuzer", 4, 1),
    ("Zerstörer", 3, 2),
    ("U-Boot", 2, 1),
    ("Flugzeugträger", 5, 1, "carrier_l")
]

# Spielzustaende
STATE_MENU = "menu"
STATE_PLACEMENT = "placement"
STATE_BATTLE = "battle"
STATE_GAME_OVER = "game_over"

# Zell-Status
CELL_EMPTY = 0
CELL_SHIP = 1
CELL_HIT = 2
CELL_MISS = 3
CELL_DESTROYED = 4

# Schiffs-Orientierung
ORIENTATION_HORIZONTAL = 0
ORIENTATION_VERTICAL = 1

# Text-Einstellungen
FONT_SIZE_TITLE = 48
FONT_SIZE_LARGE = 32
FONT_SIZE_MEDIUM = 24
FONT_SIZE_SMALL = 18

# Menu UI
MENU_BUTTON_WIDTH = 400
MENU_BUTTON_HEIGHT = 80
MENU_BUTTON_Y = 650
MENU_BUTTON_SPACING = 120
MENU_TITLE_FONT_SIZE = 120
MENU_SUBTITLE_FONT_SIZE = 60
MENU_INFO_FONT_SIZE = 24
MENU_TITLE_Y = 150
MENU_SUBTITLE_Y = 300
MENU_INFO_MARGIN_BOTTOM = 30

# Placement UI
PLACEMENT_PANEL_WIDTH = 1000
PLACEMENT_PANEL_HEIGHT = 80
PLACEMENT_PANEL_Y = 20
PLACEMENT_TITLE_FONT_SIZE = 56
PLACEMENT_INSTRUCTION_FONT_SIZE = 36
PLACEMENT_INSTRUCTION_MARGIN_BOTTOM = 60
PLACEMENT_PROGRESS_PANEL_WIDTH = 350
PLACEMENT_PROGRESS_PANEL_HEIGHT = 60
PLACEMENT_PROGRESS_PANEL_MARGIN_RIGHT = 50
PLACEMENT_PROGRESS_PANEL_Y = 120
PLACEMENT_PROGRESS_FONT_SIZE = 32
PLACEMENT_SHIP_LIST_X = 100
PLACEMENT_SHIP_LIST_MARGIN_BOTTOM = 350
PLACEMENT_SHIP_LIST_WIDTH = 350
PLACEMENT_SHIP_LIST_HEIGHT = 300
PLACEMENT_SHIP_LIST_TITLE_FONT_SIZE = 32
PLACEMENT_SHIP_LIST_ITEM_FONT_SIZE = 24
PLACEMENT_SHIP_LIST_ITEM_SPACING = 40
PLACEMENT_PREVIEW_INSET = 2

# Battle UI
BATTLE_PANEL_WIDTH = 1200
BATTLE_PANEL_HEIGHT = 80
BATTLE_PANEL_Y = 20
BATTLE_STATUS_FONT_SIZE = 48
BATTLE_HEADER_FONT_SIZE = 42
BATTLE_LABEL_FONT_SIZE = 28
BATTLE_STAT_PANEL_WIDTH = 450
BATTLE_STAT_PANEL_HEIGHT = 80
BATTLE_STAT_PANEL_OFFSET_Y = 50
BATTLE_STAT_FONT_SIZE = 32
BATTLE_AIRSTRIKE_BUTTON_WIDTH = 300
BATTLE_AIRSTRIKE_BUTTON_HEIGHT = 60
BATTLE_AIRSTRIKE_BUTTON_MARGIN_BOTTOM = 80
BATTLE_COMPUTER_DELAY_TIME = 1.0

# Game Over UI
GAME_OVER_BUTTON_WIDTH = 300
GAME_OVER_BUTTON_HEIGHT = 60
GAME_OVER_BUTTON_SPACING = 100
GAME_OVER_TITLE_Y = 250
GAME_OVER_TITLE_FONT_SIZE = 100
GAME_OVER_SUBTITLE_Y = 350
GAME_OVER_SUBTITLE_FONT_SIZE = 48
GAME_OVER_STATS_Y = 420
GAME_OVER_STATS_FONT_SIZE = 36
GAME_OVER_ICON_MARGIN_BOTTOM = 50
GAME_OVER_ICON_FONT_SIZE = 32


def update_layout(width=None, height=None):
    """Aktualisiert layoutabhaengige Werte."""
    global WINDOW_WIDTH, WINDOW_HEIGHT, PLAYER_GRID_X, COMPUTER_GRID_X, GRID_OFFSET_Y
    if width is not None:
        WINDOW_WIDTH = int(width)
    if height is not None:
        WINDOW_HEIGHT = int(height)

    PLAYER_GRID_X = WINDOW_WIDTH // 2 - GRID_GAP_X - (GRID_SIZE * CELL_SIZE)
    COMPUTER_GRID_X = WINDOW_WIDTH // 2 + GRID_GAP_X
    GRID_OFFSET_Y = GRID_TOP_MARGIN


def update_fullscreen(enabled=False, changed=False):
    global WINDOW_FULLSCREEN, WINDOW_FULLSCREEN_CHANGED
    WINDOW_FULLSCREEN = enabled
    WINDOW_FULLSCREEN_CHANGED = changed


update_layout(WINDOW_WIDTH, WINDOW_HEIGHT)
